import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { compileFromFile } from 'json-schema-to-typescript';
import prettier from 'prettier';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(currentDir, '../../..');
const schemaDir = path.join(repoRoot, 'schemas/v1');
const generatedDir = path.join(repoRoot, 'packages/schema/src/generated/v1');

const header = [
  '// Generated by packages/schema/scripts/generate.mjs.',
  '// Do not edit this file manually.',
  '',
].join('\n');
const prettierConfig = {
  printWidth: 100,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
};

async function formatTypeScript(source) {
  return prettier.format(source, {
    ...prettierConfig,
    parser: 'typescript',
  });
}

const schemaFiles = (await readdir(schemaDir))
  .filter((file) => file.endsWith('.schema.json') && file !== 'shared.schema.json')
  .sort();
const exportedTypes = new Map([
  ['alignment.schema.json', 'TrackAlignment'],
  ['control-point.schema.json', 'ElevationControlPoint'],
  ['dataset.schema.json', 'Railway3DDataset'],
  ['line.schema.json', 'RailwayLine'],
  ['manifest.schema.json', 'Railway3DDatasetManifest'],
  ['operator.schema.json', 'RailwayOperator'],
  ['profile.schema.json', 'ElevationProfile'],
  ['route.schema.json', 'RailwayRoute'],
  ['segment.schema.json', 'RailwaySegment'],
  ['source.schema.json', 'Railway3DDataSource'],
  ['station.schema.json', 'RailwayStation'],
]);

await mkdir(generatedDir, { recursive: true });

const localSchemaDir = await mkdtemp(path.join(os.tmpdir(), 'railway3d-schema-'));
const allSchemaFiles = (await readdir(schemaDir)).filter((file) => file.endsWith('.schema.json'));

for (const schemaFile of allSchemaFiles) {
  const schemaText = await readFile(path.join(schemaDir, schemaFile), 'utf8');
  await writeFile(
    path.join(localSchemaDir, schemaFile),
    schemaText.replaceAll('https://railway3d.dev/schemas/v1/', ''),
    'utf8',
  );
}

for (const schemaFile of schemaFiles) {
  const outputFile = path.join(generatedDir, schemaFile.replace('.schema.json', '.ts'));
  const compiled = await compileFromFile(path.join(localSchemaDir, schemaFile), {
    bannerComment: '',
    cwd: localSchemaDir,
    enableConstEnums: false,
    style: {
      semi: true,
      singleQuote: true,
      trailingComma: 'all',
    },
    unreachableDefinitions: false,
  });
  await writeFile(outputFile, await formatTypeScript(`${header}${compiled}`), 'utf8');
}

await rm(localSchemaDir, { recursive: true, force: true });

await writeFile(
  path.join(repoRoot, 'packages/schema/src/generated/v1/index.ts'),
  await formatTypeScript(
    `${header}${schemaFiles
      .map((file) => {
        const typeName = exportedTypes.get(file);
        if (typeName === undefined) {
          throw new Error(`Missing exported type mapping for ${file}`);
        }
        return `export type { ${typeName} } from './${file.replace('.schema.json', '')}';`;
      })
      .join('\n')}\n`,
  ),
  'utf8',
);

console.log(`Generated TypeScript types for ${schemaFiles.length} Railway3D schemas.`);
